//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRY.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Count { get; set; }
        public byte[] Img { get; set; }
        public string Category { get; set; }

        public HttpPostedFileBase File { get; set; }
    }
}
